events {
    worker_connections 1024;
}

http {
    server {
      listen 80;
      server_name staging.bms-fe.janmang.me;
      location / {
        proxy_pass http://localhost:3000;
      }
    }   

    server {
      listen 80;
      server_name staging.bms-ws.janmang.me;
      location / {
        proxy_pass http://localhost:3001;
      }
    }  

    server {
      listen 80;
      server_name staging.bms-http.janmang.me;
      location / {
        proxy_pass http://localhost:3002;
      }
    }  

}